name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@master
    name: Build and test
        run: |
          cd GitHubActionsTest/githubactionstest
          xcodebuild -workspace githubactionstest.xcworkspace -scheme githubactionstest -destination 'generic/platform=iOS'
